# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.4

# Mod Properties
mod_version=2.2.1-1.21.5
maven_group=walksy.consumableoptimizer
archives_base_name=ConsumableOptimizer

# Dependencies
fabric_version=0.145.2+26.1.1
walksylib_version=1.0.4+26.1
